(fix) switch to bash in curlimage

diff --git a/charts/antaeus/templates/tests/test_antaeus_up.yaml b/charts/antaeus/templates/tests/test_antaeus_up.yaml
--- a/charts/antaeus/templates/tests/test_antaeus_up.yaml
+++ b/charts/antaeus/templates/tests/test_antaeus_up.yaml
@@ -11,9 +11,10 @@ spec:
   - name: {{ .Release.Name }}-test-antaeus-up
     image: curlimages/curl
     command:
-      - /bin/sh
+      - /bin/bash
       - -ec
       - |
+        echo -e "► Starting tests"
         TEST_HOST=antaeus-service:8080
         TEST_PATHS=$(cat <<'EOT'
         rest/health
@@ -25,32 +26,31 @@ spec:
         )
         TMPF="/tmp/content.txt"
         touch $TMPF
-
         if test -f "$TMPF"; then
-            echo "  Buffer file $TMPF exists."
+          echo "  Buffer file $TMPF exists."
         else
-            echo "  Can't create buffer file $TMPF aborting tests."
-            exit 1
+          echo "  Can't create buffer file $TMPF aborting tests."
+          exit 1
         fi
         echo -e "► Testing API Endpoints:"
         for p in $TEST_PATHS
         do
-            TEST_URL="http://${TEST_HOST}/${p}"
-            echo -e -n "► Testing ${TEST_URL} ..."
-            HTTP_STATUS=""
-            HTTP_STATUS=$(curl -k -L -X GET -q --max-time 5 -s -w '%{http_code}' -o ${TMPF} ${TEST_URL})
-            CONTENT=$(< ${TMPF})
-            if [ $HTTP_STATUS -ne 200 ]
-            then
-                echo -e " X Failed [$HTTP_STATUS]"
-                echo -e "  Got: $CONTENT"
-                echo -e "  Antaeus service is quite slow to build ~1 minute or something is really wrong, check and try again."
-                exit 1
-            else
-                echo -e " ✔ Passed [$HTTP_STATUS]"
-                echo -e "  ---\n  $CONTENT\n  ---"
-            fi
-            echo -e "  ✔ Done"
+          TEST_URL="http://${TEST_HOST}/${p}"
+          echo -e -n "► Testing ${TEST_URL} ..."
+          HTTP_STATUS=""
+          HTTP_STATUS=$(curl -k -L -X GET -q --max-time 5 -s -w '%{http_code}' -o ${TMPF} ${TEST_URL})
+          CONTENT=$(< ${TMPF})
+          if [ $HTTP_STATUS -ne 200 ]
+          then
+              echo -e " X Failed [$HTTP_STATUS]"
+              echo -e "  Got: $CONTENT"
+              echo -e "  Antaeus service is quite slow to build ~1 minute or something is really wrong, check and try again."
+              exit 1
+          else
+              echo -e " ✔ Passed [$HTTP_STATUS]"
+              echo -e "  ---\n  $CONTENT\n  ---"
+          fi
+          echo -e "  ✔ Done"
         done
         echo -e "✔ All Tests Done"
   restartPolicy: Never
